export const idpsRuleSeeds = [
  {
    ruleId: 10001,
    status: false,
    description: 'Block',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'UDP',
    action: 'drop',
    severity: 1,
  },
  {
    ruleId: 10002,
    status: true,
    description: 'Drop',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'TCP',
    action: 'alert',
    severity: 2,
  },
  {
    ruleId: 10003,
    status: false,
    description: 'Block',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'ICMP',
    action: 'drop',
    severity: 1,
  },
  {
    ruleId: 10004,
    status: true,
    description: 'Drop',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'IP',
    action: 'alert',
    severity: 2,
  },
  {
    ruleId: 10005,
    status: false,
    description: 'Block',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'ICMP',
    action: 'drop',
    severity: 1,
  },
  {
    ruleId: 10006,
    status: true,
    description: 'Drop',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'TCP',
    action: 'alert',
    severity: 2,
  },
  {
    ruleId: 10007,
    status: false,
    description: 'Block',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'UDP',
    action: 'drop',
    severity: 1,
  },
  {
    ruleId: 10008,
    status: true,
    description: 'Drop',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'TCP',
    action: 'alert',
    severity: 2,
  },
  {
    ruleId: 10009,
    status: false,
    description: 'Block',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'ICMP',
    action: 'drop',
    severity: 1,
  },
  {
    ruleId: 10010,
    status: true,
    description: 'Drop',
    sourceIp: 'any',
    destinationIp: 'any',
    sourcePort: 'any',
    destinationPort: 'any',
    protocol: 'IP',
    action: 'alert',
    severity: 2,
  },
];